Fix default validation without regex
dkijkuit/checkheadersplugin pull request #9
Opened 2023-11-27 11:26 UTC by frankforpresident

While testing the plugin I've notice that the default behaviour was not working anymore.

I've testing it locally and fixed the bug

2023-11-27 12:48 UTC, frankforpresident commented
I didn't understand why this was introduced while the tests were passing but I had another look at unit tests and I've noticed that the negative tests will never work like this because it will always be rejected when one header value turns 403. 

I would recommend to update the negative tests to validate every header value one by one and see if it will return 403 independently. Currently if one value returns 200 it will not be catched by TestHeadersNotMatch

2023-11-27 13:11 UTC, frankforpresident commented
I've added an extra unit test to prevent this bug in the future.

2023-11-29 14:22 UTC, frankforpresident commented
@dkijkuit,

I've added "matchtype none" which provides me with enough flexibility to no use the regexp2 package. 

All tests passed and I've tested it locally

2023-12-06 07:18 UTC, frankforpresident commented
@dkijkuit,

Could you please have a look?

2023-12-13 21:29 UTC, dkijkuit commented on README.MD
> +                - "VALUE_\d"
This should be escaped as well

2023-12-13 21:31 UTC, dkijkuit commented on README.MD
> +                - "VALUE_\d"
Escape

2023-12-13 21:31 UTC, dkijkuit commented on dynamic-dev-config.yaml
> +                - "VALUE_\d"
Escape

2023-12-13 21:36 UTC, dkijkuit requested changes
Please make sure the docs are correct, ie. escaping the regex

2023-12-13 22:32 UTC, frankforpresident commented on dynamic-dev-config.yaml
> +                - "VALUE_\d"
done

2023-12-13 22:53 UTC, frankforpresident commented
> Please make sure the docs are correct, ie. escaping the regex

Done

2023-12-18 08:07 UTC, dkijkuit approved these changes

2023-12-18 08:08 UTC, merged